name: Node CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install, build, and test
              run: |
                  curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
                  yarn install
                  yarn verse
                  yarn build
                  yarn test:ci
                  yarn test --ci --debug --config jest.config.ci.js
              env:
                  CI: true
                  ALPACA_SECRET_KEY_ID: ${{ secrets.ALPACA_SECRET_KEY_ID }}
                  ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
